### ISSUE TITLE
Error on multiple sessions

### ISSUE THREAD

**Issue by mrbarnk** [smashah/sulla#141] opened 2020-02-21 23:33 UTC
**Describe the bug**
This error occurred when you try to activate multiple sessions at once.
`(node:5012) UnhandledPromiseRejectionWarning: Error: Failed to add page binding with name onMessage: window['onMessage'] already exists!`

**Steps to Reproduce**
1. Copied this code below, and run it.
2. Scan the two QR codes and make sure they are authenticated.
3. If the error didn't show, restart it with the two sessions loading together.

**create() code**
This is the code you use to create the client. e.g
```javascript
sulla.create('session_a').then(client => start(client));
sulla.create('session_b').then(client => start(client));
```

**Expected behavior**
`Session a` will load fine so as `session b`, but when you try to listen to the message again, I mean listen to `session_b` message, it brings here error of `(node:7588) UnhandledPromiseRejectionWarning: Error: Failed to add page binding with name onMessage: window['onMessage'] already exists!`

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '0.4.930',
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.24',
  BROWSER_VERSION: 'HeadlessChrome/79.0.3945.0'
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: [e.g. iOS]Windows, Moving to ubuntu cloud

**Additional context**

**Comment by smashah** [comment] 2020-03-01 16:57
@mrbarnk do you have any more information for reproduction? The current method of 'keep restarting it until it breaks' is not good enough as I'm unable to reproduce.

**Comment by JoeDozan24** [comment] 2020-03-02 06:31
I solved this by moving the `var waPage` and `var qrtimeout` inside the `create` function on initializer.js
From:
`let waPage;
let qrTimeout;
/**
 * Should be called to initialize whatsapp client
 */
export async function create(sessionId?: string, puppeteerConfigOverride?:any, customUserAgent?:string) {
  shouldLoop = true;
  if (!sessionId) sessionId = 'session';
  spinner.start('Initializing whatsapp');`

Into:
`
/**
 * Should be called to initialize whatsapp client
 */
export async function create(sessionId?: string, puppeteerConfigOverride?:any, customUserAgent?:string) {
  let waPage;
  let qrTimeout;
  shouldLoop = true;
  if (!sessionId) sessionId = 'session';
  spinner.start('Initializing whatsapp');`

But the kill() function won't work and need to be changed

**Comment by smashah** [comment] 2020-03-02 09:13
> I solved this by moving the `var waPage` and `var qrtimeout` inside the `create` function on initializer.js
> From:
> 
> COPY```
> let waPage;
> let qrTimeout;
> /**
>  * Should be called to initialize whatsapp client
>  */
> export async function create(sessionId?: string, puppeteerConfigOverride?:any, customUserAgent?:string) {
>   shouldLoop = true;
>   if (!sessionId) sessionId = 'session';
>   spinner.start('Initializing whatsapp');
> ```
> 
> Into:
> 
> COPY```
> /**
>  * Should be called to initialize whatsapp client
>  */
> export async function create(sessionId?: string, puppeteerConfigOverride?:any, customUserAgent?:string) {
>   let waPage;
>   let qrTimeout;
>   shouldLoop = true;
>   if (!sessionId) sessionId = 'session';
>   spinner.start('Initializing whatsapp');
> ```
> 
> But the kill() function won't work and need to be changed

If that's the case then setting both to undefined at the beginning of create method should work too.

**Comment by smashah** [comment] 2020-03-02 11:24
![image](https://user-images.githubusercontent.com/5903821/75672265-4fa0f180-5c78-11ea-9069-c0d3fa412a6a.png)

@mrbarnk @JoeDozan24 can you confirm if this problem is fixed with latest version please. Thanks

**Comment by JoeDozan24** [comment] 2020-03-03 06:08
Still having same problem

![image](https://user-images.githubusercontent.com/58735845/75746979-5c901480-5d4e-11ea-88d1-560173dca53f.png)

![image](https://user-images.githubusercontent.com/58735845/75747025-792c4c80-5d4e-11ea-890b-dcffc4f44a55.png)

The "client.onAnyMessage" is already binded to the first one.

if awaited, then everything is normal

![image](https://user-images.githubusercontent.com/58735845/75747632-0b812000-5d50-11ea-88c5-8d8321201745.png)

**Comment by smashah** [comment] 2020-03-03 08:26
@mrbarnk can you confirm that using await works for you?

**Comment by mrbarnk** [comment] 2020-03-03 08:29
I will check this today then.

**Comment by smashah** [comment] 2020-03-03 21:16
Closing for now. Thanks

**Closed by smashah** 2020-03-03 21:16 UTC
Labels: Requires Investigation

**Comment by impozzible** [comment] 2020-04-02 02:45
Await didnt work for me, but moving var waPage and var qrtimeout inside the create function did

**Comment by mrbarnk** [comment] 2020-04-23 19:40
Hi @smashah , sorry I couldn't test this then.

Yea, it doesn't work. Still same thing.

This happens when you run a while loop for multiple sessions.

**Comment by mrbarnk** [comment] 2020-04-24 21:27
@smashah , I think the possible solution to this is to move those variable `let waPage;` on this file https://github.com/open-wa/wa-automate-nodejs/blob/master/src/controllers/initializer.ts to 
` export async function create(sessionId?: any` method.

Please try to test that, let see if it works.

**Comment by smashah** [comment] 2020-04-25 18:05
@mrbarnk try v1.9.0

**Comment by mrbarnk** [comment] 2020-04-25 18:44
Thanks, bro, it works.
