### ISSUE TITLE
Tos Blocked error after scanning qrcode ,if run code again

### ISSUE THREAD

**Issue by BanwaitKaran** [smashah/sulla#148] opened 2020-02-27 23:05 UTC
**Describe the bug**
I scanned qrcode and after closing running code, i ran again and getting error TosBlocked.
2 days before this one working fine. However today i getting error. Due to that i have to delete every time session folder and have to scan qr code every time.

**Steps to Reproduce**
1. Run code and scan qrcode
2. close running node code.
3. Run again and get error Tos Blocked.

**create() code**
sulla.create('session',
  {
    throwErrorOnTosBlock:true,
    killTimer:600,
    autoRefresh:true,
    qrRefreshS:15 
  }
).then(async client => await start(client))
.catch(err =>console.log(err));

**Expected behavior**
Do not have to scan qrcode every time

**DEBUG INFO**
Debug Info { WA_VERSION: 'I think you have been TOS_BLOCKed',
  PAGE_UA:
   'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.28',
  BROWSER_VERSION: 'HeadlessChrome/80.0.3987.0' }

**Screenshots**
> node app.js

√ Initializing whatsapp
Debug Info { WA_VERSION: '0.4.930',
  PAGE_UA:
   'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.28',
  BROWSER_VERSION: 'HeadlessChrome/80.0.3987.0' }
i Authenticate to continue
√ Loading QR

▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █ ▀██▄▄▄█  ███▄▀▄█ ▄█▀▄ ███ ▄▄▄▄▄ █
█ █   █ ███▀▄▀ ██ ▄ █ ▄▀▄▀  █ ▄▀▄ █ █   █ █
█ █▄▄▄█ █ ▀▄█▄█▀▄█ ▀▄▀▄ █▄▄ ██▀██▀█ █▄▄▄█ █
█▄▄▄▄▄▄▄█ █ ▀▄█▄▀▄█ █ █▄█ █▄▀▄█▄▀▄█▄▄▄▄▄▄▄█
█ ▄ █▀ ▄█ ▄ █  ▀ █ █ █▀█▄ ▀ █ ▄█▄▀▄  ▄██▄ █
█▀ ▀ ▄▀▄ ▄█ █▄▄▀▄ ▄▄▄█▄█ ██  █▄█▄█  █  ██ █
█▄ ▀▄██▄██▀▀▄██    █▀▀▄█ ███ ▀ █▀ █▄ █ ▀  █
█ █  █▀▄ ▀▄ ▄██▀▄█▄  ▄▄ ▄ ▄ ▄ ██ ▄   ████▄█
█ ▀▄█ ▀▄  ▄█ ▀ ▀▄▀██▄▀▀▀▀▀▀▀ ▀▄▀▀█▀▄▀▄▄▀▄▄█
██ ██▄█▄ ▀▀█ ▄▄▀▄▀▄█ ▄█▄ █▄▀▄▀▄ ▄██▄▄▄ ▄█▄█
██▀▄▄▀█▄█ ██▀ █▄▄▄█▀  ▄▀▄▀▄▀▄██  █▀ ▄█▀█▀▄█
█▀▄   ▀▄▄▄█ ▀█▀██  █ ▀▀ █ ▀██ ▄▀▄▀▀▄▀█ █  █
█▀▄█ ▄▄▄▄█ ▄  ▀█▄▄█▀  ▄  ██   █  ▀ ▄  ▀█▄▄█
██▀▀██ ▄▀▄█▄▄█▄█▄▀ ▀  ▄▀ █▀█▄ ██▀▀   █▀█▀▀█
█▄▄▄▄█▀▄▄▄ █▄██  ▀▄█ ███ ▀▄  ██  █▄▄███▄▄▄█
█▄▄▄██▄▄▄▀ ▄  ██ ▀▄█▄ ▄██ ▀█  ▀ █ ▄▄▄ ▀█▄▄█
█ ▄▄▄▄▄ █▀ █ █▄ ▄ █▀▄▄█ ▄ ██ ▄██  █▄█  ██ █
█ █   █ ██ ▄█   ▄▀▄█▀▀▀█  ▀ ▄▀▄█ ▄ ▄▄ ▀██▄█
█ █▄▄▄█ █ █▄▀ ██▄▄█▀▄▀█ ▄▄█▀▄▀██▄▄█ █ ▀█▄██
█▄▄▄▄▄▄▄█▄▄▄█▄█▄█▄███▄▄█▄██▄▄▄▄██▄█▄█▄█▄█▄█

√ Authenticating
√ WAPI Reinjected
√ Whatsapp is ready
starting

Terminate batch job (Y/N)? ERROR: The process with PID 3684 (child process of PID 7848) could not be terminated.
Reason: There is no running instance of the task.

^C
PS whatsapp-bot> npm start

> whatsappbot@1.1.1 start whatsapp-bot
> node app.js

√ Initializing whatsapp
Debug Info { WA_VERSION: 'I think you have been TOS_BLOCKed',
  PAGE_UA:
   'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.28',
  BROWSER_VERSION: 'HeadlessChrome/80.0.3987.0' }
Error: TOSBLOCK
    at Object.<anonymous> (whatsapp-bot\node_modules\sulla-hotfix\dist\controllers\initializer.js:98:31)
    at step (whatsapp-bot\node_modules\sulla-hotfix\dist\controllers\initializer.js:33:23)
    at Object.next (whatsapp-bot\node_modules\sulla-hotfix\dist\controllers\initializer.js:14:53)
    at fulfilled (whatsapp-bot\node_modules\sulla-hotfix\dist\controllers\initializer.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Terminate batch job (Y/N)? ERROR: The process with PID 6224 (child process of PID 7572) could not be terminated.
Reason: There is no running instance of the task.

^C

**Host (please complete the following information):**
 - Window 10 home and ubuntu 18.04.1: [e.g. iOS]

**Comment by JoeDozan24** [comment] 2020-02-28 07:12
as far I see using `headless: false`, the WhatsApp on Puppeteer seems not recognizing the Browser.. or maybe caused of its cache
![image](https://user-images.githubusercontent.com/58735845/75518743-3576d180-5a34-11ea-8087-19e9d770dff7.png)
if you did the `Shift + F5` on it, it will continue normally to WhatsApp

**Comment by smashah** [comment] 2020-02-28 10:35
Thanks for filling in the template. Duplicate of #110. Continue discussion there.

**Closed by smashah** 2020-02-28 10:35 UTC
