### ISSUE TITLE
sendLocation not working

### ISSUE THREAD

**Issue by mcroni** [smashah/sulla#193] opened 2020-03-07 00:56 UTC
**Describe the bug**

**Steps to Reproduce**
```
async function start(client) {
    await client.onMessage(message => {
        console.log(message);

        if (message.body === 'Hi') {
            client.sendText(message.from, '👋 Hello!');
            client.sendLocation(message.from, '51.5074', '0.1278',  'LONDON!');

        }
    });
}



```

**create() code**
This is the code you use to create the client. e.g
```javascript
create('session',
    {
        headless: false,
        executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
    },
        "WhatsApp/0.4.315 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"
    )
    .then(client => start(client));
```

**Expected behavior**
I wish i could find a working code example for sendLocation and the sendImage/File function. When i do this the code doesnt throw any error and yet i dont see the location been sent nor the file being sent to the reciepient

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '0.4.1296',
  PAGE_UA: 'WhatsApp/0.4.315 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.28',
  BROWSER_VERSION: 'Chrome/80.0.3987.132'
}
```

**Host (please complete the following information):**
 - OS: [e.g. Windows]

**Comment by marcelocecin** [comment] 2020-03-07 12:00
same errors here

**Comment by smashah** [comment] 2020-03-07 12:49
Can you check if there are any errors in the chrome console

**Comment by andersondeoliveiramachado** [comment] 2020-03-07 14:10
![image](https://user-images.githubusercontent.com/1152426/76144974-0e3b8800-6064-11ea-8444-ef7ce5fe0934.png)

location sending worked with the latest version of WAPI on the console. the SendText function is undefined.

**Comment by smashah** [comment] 2020-03-07 15:22
sendText isn't a wapi function

**Comment by mcroni** [comment] 2020-03-07 17:04
@smashah  i tried `WAPI.sendLocation("23327xxxxxxx@c.us",5.55602, -0.1969, "accra")` which only returns a `Promise {<resolved>: undefined}` in the console

**Comment by irhampro** [comment] 2020-03-07 17:52
@smashah I got same error.. `sendFile()` didnt post anything. In console it return `Promise {<pending>}`
![Untitled](https://user-images.githubusercontent.com/55399888/76149893-141e8100-60d7-11ea-854e-444c83081804.png)

**Comment by mcroni** [comment] 2020-03-07 17:56
@irhampro i think you can use `sendImage` to achieve the same purpose, i just tried it and it works, i think @smashah  stated in the readme that this words.
`await whatsapp.sendImage(
                    message.from,
                    "data:binary/octet-stream;base64,UEsDBAoAAAAAAIdO4kAAAAAAAAAAAAAAAAAJAAAAZG9jUHJvcHMvUEsDBBQAAAAIAIdO4kBWLtLiXgEAAHECAAAQAAAAZG9jUHJvcHMvYXBwLnhtbJ2RwW7CMBBE75X6D1HuiZ1AKCBjREM5VS0SoRyR5SzEamJbtkHw93VIBem1t51Zefy0Q+aXpg7OYKxQchYmMQ4DkFyVQh5n4bZYReMwsI7JktVKwiy8gg3n9PmJrI3SYJwAG/gIaWdh5ZyeImR5BQ2zsV9Lvzko0zDnpTkidTgIDkvFTw1Ih1KMRwguDmQJZaTvgWGXOD27/4aWird89qu4ag9MSQGNrpkD+tHi1HGpXEPQ3SVrdgRLE4K6geyUKS3FBHUDyStmGHf+Tq3ZU+RdSP/Sm93gkww7Gqarm9lTpFCO1YVogGYD//ddkQ1nNeSelx5YbYGgh9HGf9utLtSypf/d/zV7cDvhqo1mvCN6YPZ8stC6Fpw5XzjdrTfB562UfZLEaYzj8WSS7FfJ2yB9ec2jdDTJo+EgK6NFkqURzvJsiMc===",
                    "mcroni.docx",
                    `You just sent me this`
                );`

this isnt a valid base64 but this works for me

**Comment by irhampro** [comment] 2020-03-07 18:26
My `sendFile()` is working right now.. I just forgot to put mime before base64 string. Also work with `sendImage()` thx @mcroni .

**Comment by mcroni** [comment] 2020-03-07 18:26
this is really strange, now the sendLocation works on both web and can be seen on the receipient's phone. 
![Capture](https://user-images.githubusercontent.com/9542980/76150332-339ab700-60a1-11ea-9872-b6582e4fb9dc.PNG)

**Comment by smashah** [comment] 2020-03-08 14:56
Ok I'll close this for now then. Please report back if it happens again. Thanks

**Comment by marcelocecin** [comment] 2020-03-09 10:35
the `sendGiphy` error:
Access to XMLHttpRequest at 'https://mmg-fna.whatsapp.net/mms/gif/2qXYcoSC_0B5890NHbe_NzDoa0maNCjb5CftFqwxuvY=?auth=AWR7BpNmyLgWD0iI3uJIxWygWWJ2DNwDesmNLVBTaoz7YPylGA0MB5vxjls&token=2qXYcoSC_0B5890NHbe_NzDoa0maNCjb5CftFqwxuvY%3D&resume=1' from origin 'https://web.whatsapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by marcelocecin** [comment] 2020-03-09 10:37
the `sendLocation` error:
Uncaught (in promise) Error: MsgKey error: something's not a wid: from:xxxxxx@c.us to:yyyyyy@c.us p:yyyyyy@c.us
    at new e (app2.a9872fe34c195f62f27b.js:2)
    at t.value (app2.a9872fe34c195f62f27b.js:2)
    at l (app2.a9872fe34c195f62f27b.js:2)
    at a (app2.a9872fe34c195f62f27b.js:2)
    at app2.a9872fe34c195f62f27b.js:2
    at Array.forEach (<anonymous>)
    at t.default (app2.a9872fe34c195f62f27b.js:2)
    at t.default (app2.a9872fe34c195f62f27b.js:2)
    at app.a8aee3263acf3b647bd5.js:2

**Comment by mcroni** [comment] 2020-03-09 10:40
the `sendLocation` doesn't seem to work all the time,  @marcelocecin  can you kindly paste an example code to help us with better debugging

**Comment by marcelocecin** [comment] 2020-03-09 16:04
I'm using the `server.ts` demo

**Comment by smashah** [comment] 2020-03-10 12:53
I am unable to recreate this, everything seems to be working fine based on demo/index.ts

I'm going to instigate a new release, please update and try again.

@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment('🤖 JOB DONE \n' +result);
  })();
```
</details>

**Comment by smashah** [comment] 2020-03-10 12:55
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment('🤖 JOB DONE \n' +result);
  })();
```
</details>

**Comment by smashah** [comment] 2020-03-10 12:56
🤖 JOB DONE 
# Changelog

## 🚀 Release [1.8.15](https://github.com/smashah/sulla/compare/1.8.14...1.8.15) (2020-03-10)

- Bump release-it from 13.0.1 to 13.0.2 [`#199`](https://github.com/smashah/sulla/pull/199)
- Release 1.8.15 [`5e0b8b8`](https://github.com/smashah/sulla/commit/5e0b8b81581d2a0f5293ca8b8791e6bfc63c3cbe)
- update wapi. location, gifs tested to be working. #193 [`86806bd`](https://github.com/smashah/sulla/commit/86806bd3f70da27ba48aca419d0237e3c08323b2)

**Closed** 2020-03-10 12:56 UTC

**Comment by marcelocecin** [comment] 2020-03-10 13:56
still with error:

vendor1.d7aea56a0442ed48f400.js:12 Error: MsgKey error: something's not a wid: from:xxxxxx@c.us to:yyyyy@c.us p:undefined
    at new e (app2.a9872fe34c195f62f27b.js:2)
    at Object.t.createQuotedMsg (app2.a9872fe34c195f62f27b.js:2)
    at t.value [as _getQuotedMsgObj] (app2.a9872fe34c195f62f27b.js:2)
    at t.value [as quotedMsgObj] (app2.a9872fe34c195f62f27b.js:2)
    at o.value (app.a8aee3263acf3b647bd5.js:2)
    at t.value (app2.a9872fe34c195f62f27b.js:2)
    at t.value (app2.a9872fe34c195f62f27b.js:2)
    at mo (vendor1.d7aea56a0442ed48f400.js:12)
    at bo (vendor1.d7aea56a0442ed48f400.js:12)
    at ql (vendor1.d7aea56a0442ed48f400.js:12)
No @ vendor1.d7aea56a0442ed48f400.js:12
Xo.a.componentDidCatch.n.callback @ vendor1.d7aea56a0442ed48f400.js:12
Vi @ vendor1.d7aea56a0442ed48f400.js:12
Fi @ vendor1.d7aea56a0442ed48f400.js:12
(anonymous) @ vendor1.d7aea56a0442ed48f400.js:12
t.unstable_runWithPriority @ vendor1.d7aea56a0442ed48f400.js:20
si @ vendor1.d7aea56a0442ed48f400.js:12
Wl @ vendor1.d7aea56a0442ed48f400.js:12
Nl @ vendor1.d7aea56a0442ed48f400.js:12
(anonymous) @ vendor1.d7aea56a0442ed48f400.js:12
t.unstable_runWithPriority @ vendor1.d7aea56a0442ed48f400.js:20
si @ vendor1.d7aea56a0442ed48f400.js:12
pi @ vendor1.d7aea56a0442ed48f400.js:12
hi @ vendor1.d7aea56a0442ed48f400.js:12
Ol @ vendor1.d7aea56a0442ed48f400.js:12
enqueueSetState @ vendor1.d7aea56a0442ed48f400.js:12
x.setState @ vendor1.d7aea56a0442ed48f400.js:31
e.handleOpenChat @ app2.a9872fe34c195f62f27b.js:2
(anonymous) @ app.a8aee3263acf3b647bd5.js:2
value @ app.a8aee3263acf3b647bd5.js:2
value @ app.a8aee3263acf3b647bd5.js:2
(anonymous) @ app.a8aee3263acf3b647bd5.js:2
re @ app.a8aee3263acf3b647bd5.js:2
P @ app.a8aee3263acf3b647bd5.js:2
value @ app.a8aee3263acf3b647bd5.js:2
value @ app.a8aee3263acf3b647bd5.js:2
value @ app.a8aee3263acf3b647bd5.js:2
(anonymous) @ app2.a9872fe34c195f62f27b.js:2
oe @ app.a8aee3263acf3b647bd5.js:2
ae @ app.a8aee3263acf3b647bd5.js:2

**Comment by smashah** [comment] 2020-03-10 14:06
@marcelocecin despite the error, did it show up? That can also happen when there's a corrupted message in the chat. I suggest deleting the chat, trying again and ignoring that message if the message actually gets sent properly. Until I have reproducible instructions there's not much else I can do.
