### ISSUE TITLE
Send image not work

### ISSUE THREAD

**Issue by gildastema** [smashah/sulla#135] opened 2020-02-20 08:35 UTC
**Describe the bug**

**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
```javascript
sulla.create(...)
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: ...,
  PAGE_UA: ...,
  SULLA_HOTFIX_VERSION: ...,
  BROWSER_VERSION: ...
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**

**Additional context**

**Comment by gildastema** [comment] 2020-02-20 08:36
Send image not work not error return

**Comment by smashah** [comment] 2020-02-20 09:00
Duplicate of #78 and completely out of line to not even try to follow the template. Don't just dump issues here like this.

**Closed by smashah** 2020-02-20 09:00 UTC
