### ISSUE TITLE
How to use sulla session to send message to new number

### ISSUE THREAD

**Issue by mrbarnk** [smashah/sulla#206] opened 2020-03-11 16:41 UTC
Hi guys, do anybody knows how to use sulla session to send message to a new number?

**Comment by smashah** [comment] 2020-03-11 16:52
Duplicate of #6  #101 #25 and #112

and is clearly stated in the docs:
https://github.com/smashah/sulla#starting-a-conversation

**Closed by smashah** 2020-03-11 16:52 UTC
